name: 'Terraform PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan output'
author: 'Rob Burger'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output'
    required: true
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
runs:
  using: "composite"
  steps:
#    - name: Pull
#      uses: actions/checkout@v2
#      with:
#        ref: ${{ github.event.deployment.ref }}
#        lfs: true
    - run: echo -e '${{ inputs.commenter_input }}' > tf.out
      shell: bash
      name: Write terraform output to file
    - run: docker build -t commenter https://github.com/GetTerminus/terraform-pr-commenter.git#use-intermediate-file
      shell: bash
      name: Build commenter docker image
    - run: |
        # must enumerate all env vars we want to pass into docker, sadly.
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT='${{ toJSON(github.event) }}' \
        commenter ${{ inputs.commenter_type }} tf.out ${{ inputs.commenter_exitcode }}
      shell: bash
      name: Run commenter image

